#+title: SLIP-39/BIP-39 Phassphrase
#+OPTIONS: toc:nil title:nil author:nil

#+BEGIN_ABSTRACT
BIP-39 Seed Phrases are often protected by a Passphrase, to partially offset their insecurity.  This
often makes the Seed unrecoverable, because the Passphrase can be so easily lost or forgotten.

SLIP-39 Mnemonic Card Groups are *much* more reliable (to recover) and secure (against accidental
disclosure); a Passphrase is *not* recommended.  Leave it empty!
#+END_ABSTRACT

* BIP-39 Passphrase

  Since anyone who sees a BIP-39 phrase can immediately attempt to recover the Seed, it is often
  considered necessary to use a Passphrase.

  It is estimated that 20%+ of all Cryptocurrency has been lost, often because the BIP-39 Mnemonic is
  available but the Passphrase has been lost.

* SLIP-39 Passphrase

  If you use SLIP-39 Mnemonic Card Groups, it is usually not necessary to use a Passphrase.

  Since SLIP-39's security is so much greater (chance of accidentally disclosing your Seed is so low
  compared to BIP-39), no hardware wallet vendor has implemented SLIP-39 recovery Passphrase.

** Hardware Wallet Doesn't Support Passphrase

   The Trezor "Model T" doesn't presently support a SLIP-39 Passphrase.  So, if you supply one here,
   you will not be able to use it when recovering your SLIP-39 Mnemonics on your Trezor "Model T".

*** Use Trezor's "Hidden Wallets" Instead

    You can provide as many "Hidden Wallets" on your Trezor device as you wish, by entering a
    passphrase to switch between them.

    This works regardless of whether you recovered your Hardware Wallet from BIP-39 or SLIP-39.
