#+title: Controls
#+OPTIONS: toc:nil title:nil author:nil

#+BEGIN_ABSTRACT
Select an appropriate level of Controls detail.

| Backup  | Create SLIP-39 Mnemonics from existing BIP-39 Seed Phrase           |
| Create  | SLIP-39 Mnemonic creation, "Using BIP-39" wallet support            |
| Recover | Enhanced SLIP-39 creation and SLIP-39/BIP-39 recovery               |
| Pro     | Advanced Seeds, conversion of BIP-39 Phrase + passphrase to SLIP-39 |
#+END_ABSTRACT

* Backup

  The simplest mode, to "back up" a BIP-39 Seed Phrase Mnemonic to SLIP-39 Mnemonic Card Groups.

  Once you print, test recovery and distribute the SLIP-39 Mnemonic Cards, you can safely destroy
  your unreliable and insecure BIP-39 Seed Phrase Mnemonic backups; you can securely and reliably
  recover your BIP-39 Seed Phrase whenever you need it, by collecting a sufficient number of the
  SLIP-39 Cards.

* Create

  A basic SLIP-39 Mnemonic creation interface.  Default support for [[https://affil.trezor.io/SHdv][Trezor Safe 3]] with native
  SLIP-39 Mnemonics recovery.

  Select "Using BIP-39" for a traditional BIP-39 Seed Phrase Mnemonic, to use any other hardware
  wallets such as the [[https://shop.ledger.com/pages/ledger-nano-x?r=2cd1cb6ae51f][Ledger Nano]] (or even the Trezor, in BIP-39 Recovery mode).

* Recovery

  Greater control over the Mnemonic creation process.  Recovery of Seed Entropy from SLIP-39
  Mnemonics.

  Recover Seed Entropy from existing BIP-39 Mnemonic phrases by selecting "BIP-39 Entropy" in Seed
  Source.  

** Extra Seed Randomness

   Probably most importantly, Extra Seed Entropy can be supplied.  Any data supplied (Dice rolls,
   for example, add about 2.5 bits of entropy per roll) is hashed with a standard SHA-512 hash
   function, which can be independently confirmed.

   Finally, you can visually confirm that the Entropy is correctly applied via XOR to the Seed Data
   Source, to produce the Master Secret Seed.

   At no point do you need to "Trust" that the SLIP-39 program is producing a Master Secret Seed
   from known data!

** SLIP-39

   Supports input of existing SLIP-39 mnemonics to recover the original Seed Entropy.

*** Recover From Lost SLIP-39 Mnemonic Cards

    If you know that some of your original SLIP-39 Mnemonic cards have been lost, you can
    re-issue /another/ set of SLIP-39 cards containing the same, original Seed Entropy.

* Pro

  Advanced SLIP-39 creation and recovery, and recovery (and conversion) of BIP-39 Mnemonics to
  SLIP-39.

  Requires licensing.

** BIP-39

   Conversion of existing, fragile BIP-39 12- or 24-word Mnemonic phrases into SLIP-39 is supported.

   Enter the BIP-39 recover phrase to recover the original 128- or 256-bit Seed Entropy, and
   generate SLIP-39 Mnemonics which will recover the same Seed Entropy as the original 12- or
   24-word BIP-39 Mnemonic.
